[package]
name = "treeeee"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1.9"
clap = { version = "4.5.20", features = ["derive"] }
ignore = "0.4.23"
owo-colors = "4.1.0"
ptree = "0.5.0"

[profile.release-fast]
inherits = "release"
lto = "fat"
codegen-units = 1
