[package]
name = "treeeee"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1.7"
clap = { version = "4.5.11", features = ["derive"] }
ignore = "0.4.22"
owo-colors = "4.0.0"
ptree = "0.4.0"
